FROM rocker/shiny:4.4.2

RUN install2.r \
  rsconnect \
  ellmer \
  shinychat \
  bslib \
  dplyr \
  readr \
  purrr \
  glue \
  furrr \
  stringr \
  sass \
  future \
  Dev tools 	

WORKDIR /home/dorothy_dAI
COPY data data
COPY docs docs
COPY chat_bot.R chat_bot.R
COPY deploy_chat_bot.R deploy_chat_bot.R
CMD Rscript deploy_chat_bot.R