name: Deploy
# Controls when the action will run. 
on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t main . 
      # run the docker image supply the secrets from the github secrets store.  
      - name: execute
        run: >
          docker run
          -e NAME=${{ secrets.NAME}}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}} 
          main
